url: 'https://www.translatechat.app'
baseurl: ''
title: 'Translate Chat'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

include:
  - .well-known