url: 'https://translatechat.app'
baseurl: 'translate-chat-web'
title: 'Translate Chat'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
